<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>removeButton</name>
   <tag></tag>
   <elementGuidId>7fd8121c-418e-4cd0-b284-50835aaf67bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.cart_button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
